// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.2a_p19
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:376


#include "StockQuoterTypeSupportC.h"
#include "tao/CDR.h"
#include "ace/OS_NS_string.h"

#if !defined (__ACE_INLINE__)
#include "StockQuoterTypeSupportC.inl"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_cs.cpp:51

// Traits specializations for StockQuoter::QuoteTypeSupport.

StockQuoter::QuoteTypeSupport_ptr
TAO::Objref_Traits<StockQuoter::QuoteTypeSupport>::duplicate (
    StockQuoter::QuoteTypeSupport_ptr p)
{
  return StockQuoter::QuoteTypeSupport::_duplicate (p);
}

void
TAO::Objref_Traits<StockQuoter::QuoteTypeSupport>::release (
    StockQuoter::QuoteTypeSupport_ptr p)
{
  ::CORBA::release (p);
}

StockQuoter::QuoteTypeSupport_ptr
TAO::Objref_Traits<StockQuoter::QuoteTypeSupport>::nil (void)
{
  return StockQuoter::QuoteTypeSupport::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<StockQuoter::QuoteTypeSupport>::marshal (
    const StockQuoter::QuoteTypeSupport_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

StockQuoter::QuoteTypeSupport::QuoteTypeSupport (void)
{}

StockQuoter::QuoteTypeSupport::~QuoteTypeSupport (void)
{
}

StockQuoter::QuoteTypeSupport_ptr
StockQuoter::QuoteTypeSupport::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return QuoteTypeSupport::_duplicate (
      dynamic_cast<QuoteTypeSupport_ptr> (_tao_objref)
    );
}

StockQuoter::QuoteTypeSupport_ptr
StockQuoter::QuoteTypeSupport::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return QuoteTypeSupport::_duplicate (
      dynamic_cast<QuoteTypeSupport_ptr> (_tao_objref)
    );
}

StockQuoter::QuoteTypeSupport_ptr
StockQuoter::QuoteTypeSupport::_nil (void)
{
  return 0;
}

StockQuoter::QuoteTypeSupport_ptr
StockQuoter::QuoteTypeSupport::_duplicate (QuoteTypeSupport_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
StockQuoter::QuoteTypeSupport::_tao_release (QuoteTypeSupport_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
StockQuoter::QuoteTypeSupport::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:StockQuoter/QuoteTypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* StockQuoter::QuoteTypeSupport::_interface_repository_id (void) const
{
  return "IDL:StockQuoter/QuoteTypeSupport:1.0";
}

::CORBA::Boolean
StockQuoter::QuoteTypeSupport::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_cs.cpp:51

// Traits specializations for StockQuoter::QuoteDataWriter.

StockQuoter::QuoteDataWriter_ptr
TAO::Objref_Traits<StockQuoter::QuoteDataWriter>::duplicate (
    StockQuoter::QuoteDataWriter_ptr p)
{
  return StockQuoter::QuoteDataWriter::_duplicate (p);
}

void
TAO::Objref_Traits<StockQuoter::QuoteDataWriter>::release (
    StockQuoter::QuoteDataWriter_ptr p)
{
  ::CORBA::release (p);
}

StockQuoter::QuoteDataWriter_ptr
TAO::Objref_Traits<StockQuoter::QuoteDataWriter>::nil (void)
{
  return StockQuoter::QuoteDataWriter::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<StockQuoter::QuoteDataWriter>::marshal (
    const StockQuoter::QuoteDataWriter_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

StockQuoter::QuoteDataWriter::QuoteDataWriter (void)
{}

StockQuoter::QuoteDataWriter::~QuoteDataWriter (void)
{
}

StockQuoter::QuoteDataWriter_ptr
StockQuoter::QuoteDataWriter::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return QuoteDataWriter::_duplicate (
      dynamic_cast<QuoteDataWriter_ptr> (_tao_objref)
    );
}

StockQuoter::QuoteDataWriter_ptr
StockQuoter::QuoteDataWriter::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return QuoteDataWriter::_duplicate (
      dynamic_cast<QuoteDataWriter_ptr> (_tao_objref)
    );
}

StockQuoter::QuoteDataWriter_ptr
StockQuoter::QuoteDataWriter::_nil (void)
{
  return 0;
}

StockQuoter::QuoteDataWriter_ptr
StockQuoter::QuoteDataWriter::_duplicate (QuoteDataWriter_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
StockQuoter::QuoteDataWriter::_tao_release (QuoteDataWriter_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
StockQuoter::QuoteDataWriter::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:StockQuoter/QuoteDataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* StockQuoter::QuoteDataWriter::_interface_repository_id (void) const
{
  return "IDL:StockQuoter/QuoteDataWriter:1.0";
}

::CORBA::Boolean
StockQuoter::QuoteDataWriter::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_cs.cpp:51

// Traits specializations for StockQuoter::QuoteDataReader.

StockQuoter::QuoteDataReader_ptr
TAO::Objref_Traits<StockQuoter::QuoteDataReader>::duplicate (
    StockQuoter::QuoteDataReader_ptr p)
{
  return StockQuoter::QuoteDataReader::_duplicate (p);
}

void
TAO::Objref_Traits<StockQuoter::QuoteDataReader>::release (
    StockQuoter::QuoteDataReader_ptr p)
{
  ::CORBA::release (p);
}

StockQuoter::QuoteDataReader_ptr
TAO::Objref_Traits<StockQuoter::QuoteDataReader>::nil (void)
{
  return StockQuoter::QuoteDataReader::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<StockQuoter::QuoteDataReader>::marshal (
    const StockQuoter::QuoteDataReader_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

StockQuoter::QuoteDataReader::QuoteDataReader (void)
{}

StockQuoter::QuoteDataReader::~QuoteDataReader (void)
{
}

StockQuoter::QuoteDataReader_ptr
StockQuoter::QuoteDataReader::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return QuoteDataReader::_duplicate (
      dynamic_cast<QuoteDataReader_ptr> (_tao_objref)
    );
}

StockQuoter::QuoteDataReader_ptr
StockQuoter::QuoteDataReader::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return QuoteDataReader::_duplicate (
      dynamic_cast<QuoteDataReader_ptr> (_tao_objref)
    );
}

StockQuoter::QuoteDataReader_ptr
StockQuoter::QuoteDataReader::_nil (void)
{
  return 0;
}

StockQuoter::QuoteDataReader_ptr
StockQuoter::QuoteDataReader::_duplicate (QuoteDataReader_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
StockQuoter::QuoteDataReader::_tao_release (QuoteDataReader_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
StockQuoter::QuoteDataReader::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/DataReaderEx:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:StockQuoter/QuoteDataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* StockQuoter::QuoteDataReader::_interface_repository_id (void) const
{
  return "IDL:StockQuoter/QuoteDataReader:1.0";
}

::CORBA::Boolean
StockQuoter::QuoteDataReader::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_cs.cpp:51

// Traits specializations for StockQuoter::ExchangeEventTypeSupport.

StockQuoter::ExchangeEventTypeSupport_ptr
TAO::Objref_Traits<StockQuoter::ExchangeEventTypeSupport>::duplicate (
    StockQuoter::ExchangeEventTypeSupport_ptr p)
{
  return StockQuoter::ExchangeEventTypeSupport::_duplicate (p);
}

void
TAO::Objref_Traits<StockQuoter::ExchangeEventTypeSupport>::release (
    StockQuoter::ExchangeEventTypeSupport_ptr p)
{
  ::CORBA::release (p);
}

StockQuoter::ExchangeEventTypeSupport_ptr
TAO::Objref_Traits<StockQuoter::ExchangeEventTypeSupport>::nil (void)
{
  return StockQuoter::ExchangeEventTypeSupport::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<StockQuoter::ExchangeEventTypeSupport>::marshal (
    const StockQuoter::ExchangeEventTypeSupport_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

StockQuoter::ExchangeEventTypeSupport::ExchangeEventTypeSupport (void)
{}

StockQuoter::ExchangeEventTypeSupport::~ExchangeEventTypeSupport (void)
{
}

StockQuoter::ExchangeEventTypeSupport_ptr
StockQuoter::ExchangeEventTypeSupport::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return ExchangeEventTypeSupport::_duplicate (
      dynamic_cast<ExchangeEventTypeSupport_ptr> (_tao_objref)
    );
}

StockQuoter::ExchangeEventTypeSupport_ptr
StockQuoter::ExchangeEventTypeSupport::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return ExchangeEventTypeSupport::_duplicate (
      dynamic_cast<ExchangeEventTypeSupport_ptr> (_tao_objref)
    );
}

StockQuoter::ExchangeEventTypeSupport_ptr
StockQuoter::ExchangeEventTypeSupport::_nil (void)
{
  return 0;
}

StockQuoter::ExchangeEventTypeSupport_ptr
StockQuoter::ExchangeEventTypeSupport::_duplicate (ExchangeEventTypeSupport_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
StockQuoter::ExchangeEventTypeSupport::_tao_release (ExchangeEventTypeSupport_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
StockQuoter::ExchangeEventTypeSupport::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:StockQuoter/ExchangeEventTypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* StockQuoter::ExchangeEventTypeSupport::_interface_repository_id (void) const
{
  return "IDL:StockQuoter/ExchangeEventTypeSupport:1.0";
}

::CORBA::Boolean
StockQuoter::ExchangeEventTypeSupport::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_cs.cpp:51

// Traits specializations for StockQuoter::ExchangeEventDataWriter.

StockQuoter::ExchangeEventDataWriter_ptr
TAO::Objref_Traits<StockQuoter::ExchangeEventDataWriter>::duplicate (
    StockQuoter::ExchangeEventDataWriter_ptr p)
{
  return StockQuoter::ExchangeEventDataWriter::_duplicate (p);
}

void
TAO::Objref_Traits<StockQuoter::ExchangeEventDataWriter>::release (
    StockQuoter::ExchangeEventDataWriter_ptr p)
{
  ::CORBA::release (p);
}

StockQuoter::ExchangeEventDataWriter_ptr
TAO::Objref_Traits<StockQuoter::ExchangeEventDataWriter>::nil (void)
{
  return StockQuoter::ExchangeEventDataWriter::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<StockQuoter::ExchangeEventDataWriter>::marshal (
    const StockQuoter::ExchangeEventDataWriter_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

StockQuoter::ExchangeEventDataWriter::ExchangeEventDataWriter (void)
{}

StockQuoter::ExchangeEventDataWriter::~ExchangeEventDataWriter (void)
{
}

StockQuoter::ExchangeEventDataWriter_ptr
StockQuoter::ExchangeEventDataWriter::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return ExchangeEventDataWriter::_duplicate (
      dynamic_cast<ExchangeEventDataWriter_ptr> (_tao_objref)
    );
}

StockQuoter::ExchangeEventDataWriter_ptr
StockQuoter::ExchangeEventDataWriter::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return ExchangeEventDataWriter::_duplicate (
      dynamic_cast<ExchangeEventDataWriter_ptr> (_tao_objref)
    );
}

StockQuoter::ExchangeEventDataWriter_ptr
StockQuoter::ExchangeEventDataWriter::_nil (void)
{
  return 0;
}

StockQuoter::ExchangeEventDataWriter_ptr
StockQuoter::ExchangeEventDataWriter::_duplicate (ExchangeEventDataWriter_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
StockQuoter::ExchangeEventDataWriter::_tao_release (ExchangeEventDataWriter_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
StockQuoter::ExchangeEventDataWriter::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:StockQuoter/ExchangeEventDataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* StockQuoter::ExchangeEventDataWriter::_interface_repository_id (void) const
{
  return "IDL:StockQuoter/ExchangeEventDataWriter:1.0";
}

::CORBA::Boolean
StockQuoter::ExchangeEventDataWriter::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_cs.cpp:51

// Traits specializations for StockQuoter::ExchangeEventDataReader.

StockQuoter::ExchangeEventDataReader_ptr
TAO::Objref_Traits<StockQuoter::ExchangeEventDataReader>::duplicate (
    StockQuoter::ExchangeEventDataReader_ptr p)
{
  return StockQuoter::ExchangeEventDataReader::_duplicate (p);
}

void
TAO::Objref_Traits<StockQuoter::ExchangeEventDataReader>::release (
    StockQuoter::ExchangeEventDataReader_ptr p)
{
  ::CORBA::release (p);
}

StockQuoter::ExchangeEventDataReader_ptr
TAO::Objref_Traits<StockQuoter::ExchangeEventDataReader>::nil (void)
{
  return StockQuoter::ExchangeEventDataReader::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<StockQuoter::ExchangeEventDataReader>::marshal (
    const StockQuoter::ExchangeEventDataReader_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

StockQuoter::ExchangeEventDataReader::ExchangeEventDataReader (void)
{}

StockQuoter::ExchangeEventDataReader::~ExchangeEventDataReader (void)
{
}

StockQuoter::ExchangeEventDataReader_ptr
StockQuoter::ExchangeEventDataReader::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return ExchangeEventDataReader::_duplicate (
      dynamic_cast<ExchangeEventDataReader_ptr> (_tao_objref)
    );
}

StockQuoter::ExchangeEventDataReader_ptr
StockQuoter::ExchangeEventDataReader::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return ExchangeEventDataReader::_duplicate (
      dynamic_cast<ExchangeEventDataReader_ptr> (_tao_objref)
    );
}

StockQuoter::ExchangeEventDataReader_ptr
StockQuoter::ExchangeEventDataReader::_nil (void)
{
  return 0;
}

StockQuoter::ExchangeEventDataReader_ptr
StockQuoter::ExchangeEventDataReader::_duplicate (ExchangeEventDataReader_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
StockQuoter::ExchangeEventDataReader::_tao_release (ExchangeEventDataReader_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
StockQuoter::ExchangeEventDataReader::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/DataReaderEx:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:StockQuoter/ExchangeEventDataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* StockQuoter::ExchangeEventDataReader::_interface_repository_id (void) const
{
  return "IDL:StockQuoter/ExchangeEventDataReader:1.0";
}

::CORBA::Boolean
StockQuoter::ExchangeEventDataReader::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

