/* -*- C++ -*- */
/* Generated by /home/unichae/workspace/OpenDDS-3.14/bin/opendds_idl version 3.14 (ACE version 6.2a_p19) running on input file StockQuoter.idl */
#ifndef OPENDDS_IDL_GENERATED_STOCKQUOTERTYPESUPPORTIMPL_H_GARW0O
#define OPENDDS_IDL_GENERATED_STOCKQUOTERTYPESUPPORTIMPL_H_GARW0O
#include "StockQuoterC.h"
#include "dds/DCPS/Definitions.h"
#include "dds/DdsDcpsC.h"
#include "StockQuoterTypeSupportC.h"
#include "dds/DCPS/Serializer.h"
#include "dds/DCPS/TypeSupportImpl.h"
#include "orbsvcs/TimeBaseC.h"


/* Begin MODULE: CORBA */


/* End MODULE: CORBA */


/* Begin MODULE: TimeBase */



/* Begin TYPEDEF: TimeT */


/* End TYPEDEF: TimeT */


/* Begin TYPEDEF: InaccuracyT */


/* End TYPEDEF: InaccuracyT */


/* Begin TYPEDEF: TdfT */


/* End TYPEDEF: TdfT */


/* Begin STRUCT: UtcT */


/* End STRUCT: UtcT */


/* Begin STRUCT: IntervalT */


/* End STRUCT: IntervalT */

/* End MODULE: TimeBase */


/* Begin MODULE: StockQuoter */



/* Begin STRUCT: Quote */

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

StockQuoterCommon_Export
void gen_find_size(const StockQuoter::Quote& stru, size_t& size, size_t& padding);

StockQuoterCommon_Export
bool operator<<(Serializer& strm, const StockQuoter::Quote& stru);

StockQuoterCommon_Export
bool operator>>(Serializer& strm, StockQuoter::Quote& stru);

StockQuoterCommon_Export
size_t gen_max_marshaled_size(const StockQuoter::Quote& stru, bool align);

StockQuoterCommon_Export
size_t gen_max_marshaled_size(KeyOnly<const StockQuoter::Quote> stru, bool align);

StockQuoterCommon_Export
void gen_find_size(KeyOnly<const StockQuoter::Quote> stru, size_t& size, size_t& padding);

StockQuoterCommon_Export
bool operator<<(Serializer& strm, KeyOnly<const StockQuoter::Quote> stru);

StockQuoterCommon_Export
bool operator>>(Serializer& strm, KeyOnly<StockQuoter::Quote> stru);

template <>
struct MarshalTraits<StockQuoter::Quote> {
  static bool gen_is_bounded_size() { return false; }
  static bool gen_is_bounded_key_size() { return false; }
};
}  }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


namespace StockQuoter {
/// This structure supports use of std::map with one or more keys.
struct StockQuoterCommon_Export Quote_OpenDDS_KeyLessThan {
  bool operator()(const StockQuoter::Quote& v1, const StockQuoter::Quote& v2) const
  {
    using ::operator<; // TAO::String_Manager's operator< is in global NS
    if (v1.ticker < v2.ticker) return true;
    if (v2.ticker < v1.ticker) return false;
    return false;
  }
};
}


namespace StockQuoter {
class QuoteTypeSupportImpl;
}

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {
template <>
struct DDSTraits<StockQuoter::Quote> {
  typedef StockQuoter::Quote MessageType;
  typedef StockQuoter::QuoteSeq MessageSequenceType;
  typedef StockQuoter::QuoteTypeSupport TypeSupportType;
  typedef StockQuoter::QuoteTypeSupportImpl TypeSupportTypeImpl;
  typedef StockQuoter::QuoteDataWriter DataWriterType;
  typedef StockQuoter::QuoteDataReader DataReaderType;
  typedef StockQuoter::Quote_OpenDDS_KeyLessThan LessThanType;

  static const char* type_name () { return "StockQuoter::Quote"; }
  static bool gen_has_key () { return true; }
  static size_t key_count () { return 1; }

  static size_t gen_max_marshaled_size(const MessageType& x, bool align) { return ::OpenDDS::DCPS::gen_max_marshaled_size(x, align); }
  static void gen_find_size(const MessageType& arr, size_t& size, size_t& padding) { ::OpenDDS::DCPS::gen_find_size(arr, size, padding); }

  static size_t gen_max_marshaled_size(const OpenDDS::DCPS::KeyOnly<const MessageType>& x, bool align) { return ::OpenDDS::DCPS::gen_max_marshaled_size(x, align); }
  static void gen_find_size(const OpenDDS::DCPS::KeyOnly<const MessageType>& arr, size_t& size, size_t& padding) { ::OpenDDS::DCPS::gen_find_size(arr, size, padding); }
};
}  }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


namespace StockQuoter {
class StockQuoterCommon_Export QuoteTypeSupportImpl
  : public virtual OpenDDS::DCPS::LocalObject<QuoteTypeSupport>
  , public virtual OpenDDS::DCPS::TypeSupportImpl
{
public:
  typedef OpenDDS::DCPS::DDSTraits<Quote> TraitsType;
  typedef QuoteTypeSupport TypeSupportType;
  typedef QuoteTypeSupport::_var_type _var_type;
  typedef QuoteTypeSupport::_ptr_type _ptr_type;

  QuoteTypeSupportImpl() {}
  virtual ~QuoteTypeSupportImpl() {}

  virtual ::DDS::DataWriter_ptr create_datawriter();
  virtual ::DDS::DataReader_ptr create_datareader();
#ifndef OPENDDS_NO_MULTI_TOPIC
  virtual ::DDS::DataReader_ptr create_multitopic_datareader();
#endif /* !OPENDDS_NO_MULTI_TOPIC */
#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
  virtual const OpenDDS::DCPS::MetaStruct& getMetaStructForType();
#endif /* !OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE */
  virtual bool has_dcps_key();
  const char* default_type_name() const;
  static QuoteTypeSupport::_ptr_type _narrow(CORBA::Object_ptr obj);
};
}

#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

class MetaStruct;

template<typename T>
const MetaStruct& getMetaStruct();

template<>
StockQuoterCommon_Export
const MetaStruct& getMetaStruct<StockQuoter::Quote>();
StockQuoterCommon_Export
bool gen_skip_over(Serializer& ser, StockQuoter::Quote*);

}  }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#endif

/* End STRUCT: Quote */


/* Begin ENUM: ExchangeEventType */

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

StockQuoterCommon_Export
bool operator<<(Serializer& strm, const StockQuoter::ExchangeEventType& enumval);

StockQuoterCommon_Export
bool operator>>(Serializer& strm, StockQuoter::ExchangeEventType& enumval);

}  }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

StockQuoterCommon_Export extern const char* gen_StockQuoter_ExchangeEventType_names[];
StockQuoterCommon_Export extern const size_t gen_StockQuoter_ExchangeEventType_names_size;
}  }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


/* End ENUM: ExchangeEventType */


/* Begin STRUCT: ExchangeEvent */

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

StockQuoterCommon_Export
void gen_find_size(const StockQuoter::ExchangeEvent& stru, size_t& size, size_t& padding);

StockQuoterCommon_Export
bool operator<<(Serializer& strm, const StockQuoter::ExchangeEvent& stru);

StockQuoterCommon_Export
bool operator>>(Serializer& strm, StockQuoter::ExchangeEvent& stru);

StockQuoterCommon_Export
size_t gen_max_marshaled_size(const StockQuoter::ExchangeEvent& stru, bool align);

StockQuoterCommon_Export
size_t gen_max_marshaled_size(KeyOnly<const StockQuoter::ExchangeEvent> stru, bool align);

StockQuoterCommon_Export
void gen_find_size(KeyOnly<const StockQuoter::ExchangeEvent> stru, size_t& size, size_t& padding);

StockQuoterCommon_Export
bool operator<<(Serializer& strm, KeyOnly<const StockQuoter::ExchangeEvent> stru);

StockQuoterCommon_Export
bool operator>>(Serializer& strm, KeyOnly<StockQuoter::ExchangeEvent> stru);

template <>
struct MarshalTraits<StockQuoter::ExchangeEvent> {
  static bool gen_is_bounded_size() { return false; }
  static bool gen_is_bounded_key_size() { return false; }
};
}  }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


namespace StockQuoter {
/// This structure supports use of std::map with one or more keys.
struct StockQuoterCommon_Export ExchangeEvent_OpenDDS_KeyLessThan {
  bool operator()(const StockQuoter::ExchangeEvent& v1, const StockQuoter::ExchangeEvent& v2) const
  {
    using ::operator<; // TAO::String_Manager's operator< is in global NS
    if (v1.exchange < v2.exchange) return true;
    if (v2.exchange < v1.exchange) return false;
    return false;
  }
};
}


namespace StockQuoter {
class ExchangeEventTypeSupportImpl;
}

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {
template <>
struct DDSTraits<StockQuoter::ExchangeEvent> {
  typedef StockQuoter::ExchangeEvent MessageType;
  typedef StockQuoter::ExchangeEventSeq MessageSequenceType;
  typedef StockQuoter::ExchangeEventTypeSupport TypeSupportType;
  typedef StockQuoter::ExchangeEventTypeSupportImpl TypeSupportTypeImpl;
  typedef StockQuoter::ExchangeEventDataWriter DataWriterType;
  typedef StockQuoter::ExchangeEventDataReader DataReaderType;
  typedef StockQuoter::ExchangeEvent_OpenDDS_KeyLessThan LessThanType;

  static const char* type_name () { return "StockQuoter::ExchangeEvent"; }
  static bool gen_has_key () { return true; }
  static size_t key_count () { return 1; }

  static size_t gen_max_marshaled_size(const MessageType& x, bool align) { return ::OpenDDS::DCPS::gen_max_marshaled_size(x, align); }
  static void gen_find_size(const MessageType& arr, size_t& size, size_t& padding) { ::OpenDDS::DCPS::gen_find_size(arr, size, padding); }

  static size_t gen_max_marshaled_size(const OpenDDS::DCPS::KeyOnly<const MessageType>& x, bool align) { return ::OpenDDS::DCPS::gen_max_marshaled_size(x, align); }
  static void gen_find_size(const OpenDDS::DCPS::KeyOnly<const MessageType>& arr, size_t& size, size_t& padding) { ::OpenDDS::DCPS::gen_find_size(arr, size, padding); }
};
}  }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


namespace StockQuoter {
class StockQuoterCommon_Export ExchangeEventTypeSupportImpl
  : public virtual OpenDDS::DCPS::LocalObject<ExchangeEventTypeSupport>
  , public virtual OpenDDS::DCPS::TypeSupportImpl
{
public:
  typedef OpenDDS::DCPS::DDSTraits<ExchangeEvent> TraitsType;
  typedef ExchangeEventTypeSupport TypeSupportType;
  typedef ExchangeEventTypeSupport::_var_type _var_type;
  typedef ExchangeEventTypeSupport::_ptr_type _ptr_type;

  ExchangeEventTypeSupportImpl() {}
  virtual ~ExchangeEventTypeSupportImpl() {}

  virtual ::DDS::DataWriter_ptr create_datawriter();
  virtual ::DDS::DataReader_ptr create_datareader();
#ifndef OPENDDS_NO_MULTI_TOPIC
  virtual ::DDS::DataReader_ptr create_multitopic_datareader();
#endif /* !OPENDDS_NO_MULTI_TOPIC */
#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
  virtual const OpenDDS::DCPS::MetaStruct& getMetaStructForType();
#endif /* !OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE */
  virtual bool has_dcps_key();
  const char* default_type_name() const;
  static ExchangeEventTypeSupport::_ptr_type _narrow(CORBA::Object_ptr obj);
};
}

#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

template<>
StockQuoterCommon_Export
const MetaStruct& getMetaStruct<StockQuoter::ExchangeEvent>();
StockQuoterCommon_Export
bool gen_skip_over(Serializer& ser, StockQuoter::ExchangeEvent*);

}  }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#endif

/* End STRUCT: ExchangeEvent */

/* End MODULE: StockQuoter */
#endif /* OPENDDS_IDL_GENERATED_STOCKQUOTERTYPESUPPORTIMPL_H_GARW0O */
