// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.2a_p19
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:152

#ifndef _TAO_IDL_STOCKQUOTERC_B6S791_H_
#define _TAO_IDL_STOCKQUOTERC_B6S791_H_

#include /**/ "ace/pre.h"


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include /**/ "StockQuoterCommon_Export.h"
#include "tao/ORB.h"
#include "tao/Basic_Types.h"
#include "tao/String_Manager_T.h"
#include "tao/VarOut_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Basic_Argument_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include "tao/UB_String_Arguments.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#include "orbsvcs/TimeBaseC.h"

#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 2 || TAO_BETA_VERSION != 0
#error This file should be regenerated with TAO_IDL
#endif

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO StockQuoterCommon_Export

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:38

namespace StockQuoter
{

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct Quote;

  typedef
    ::TAO_Var_Var_T<
        Quote
      >
    Quote_var;

  typedef
    ::TAO_Out_T<
        Quote
      >
    Quote_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct StockQuoterCommon_Export Quote
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef Quote_var _var_type;
    typedef Quote_out _out_type;
    
    ::TAO::String_Manager ticker;
    ::TAO::String_Manager exchange;
    ::TAO::String_Manager full_name;
    ::CORBA::Double value;
    TimeBase::TimeT timestamp;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_enum/enum_ch.cpp:47

  enum ExchangeEventType
  {
    TRADING_OPENED,
    TRADING_CLOSED,
    TRADING_SUSPENDED,
    TRADING_RESUMED
  };

  typedef ExchangeEventType &ExchangeEventType_out;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct ExchangeEvent;

  typedef
    ::TAO_Var_Var_T<
        ExchangeEvent
      >
    ExchangeEvent_var;

  typedef
    ::TAO_Out_T<
        ExchangeEvent
      >
    ExchangeEvent_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct StockQuoterCommon_Export ExchangeEvent
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef ExchangeEvent_var _var_type;
    typedef ExchangeEvent_out _out_type;
    
    ::TAO::String_Manager exchange;
    StockQuoter::ExchangeEventType event;
    TimeBase::TimeT timestamp;
  };

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:67

} // module StockQuoter

// TAO_IDL - Generated from
// be/be_visitor_arg_traits.cpp:68

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::StockQuoter::Quote>
    : public
        Var_Size_Arg_Traits_T<
            ::StockQuoter::Quote,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:904

  template<>
  class Arg_Traits< ::StockQuoter::ExchangeEventType>
    : public
        Basic_Arg_Traits_T<
            ::StockQuoter::ExchangeEventType,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::StockQuoter::ExchangeEvent>
    : public
        Var_Size_Arg_Traits_T<
            ::StockQuoter::ExchangeEvent,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_traits.cpp:62

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

StockQuoterCommon_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const StockQuoter::Quote &);
StockQuoterCommon_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, StockQuoter::Quote &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_enum/cdr_op_ch.cpp:37


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

StockQuoterCommon_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &strm, StockQuoter::ExchangeEventType _tao_enumerator);
StockQuoterCommon_Export ::CORBA::Boolean operator>> (TAO_InputCDR &strm, StockQuoter::ExchangeEventType &_tao_enumerator);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

StockQuoterCommon_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const StockQuoter::ExchangeEvent &);
StockQuoterCommon_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, StockQuoter::ExchangeEvent &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_codegen.cpp:1703
#if defined (__ACE_INLINE__)
#include "StockQuoterC.inl"
#endif /* defined INLINE */

#include /**/ "ace/post.h"

#endif /* ifndef */

