
// -*- C++ -*-
// $Id$
// Definition for Win32 Export directives.
// This file is generated automatically by generate_export_file.pl OnboardATCSCommon
// ------------------------------
#ifndef ONBOARDATCSCOMMON_EXPORT_H
#define ONBOARDATCSCOMMON_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (ONBOARDATCSCOMMON_HAS_DLL)
#  define ONBOARDATCSCOMMON_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && ONBOARDATCSCOMMON_HAS_DLL */

#if !defined (ONBOARDATCSCOMMON_HAS_DLL)
#  define ONBOARDATCSCOMMON_HAS_DLL 1
#endif /* ! ONBOARDATCSCOMMON_HAS_DLL */

#if defined (ONBOARDATCSCOMMON_HAS_DLL) && (ONBOARDATCSCOMMON_HAS_DLL == 1)
#  if defined (ONBOARDATCSCOMMON_BUILD_DLL)
#    define OnboardATCSCommon_Export ACE_Proper_Export_Flag
#    define ONBOARDATCSCOMMON_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define ONBOARDATCSCOMMON_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* ONBOARDATCSCOMMON_BUILD_DLL */
#    define OnboardATCSCommon_Export ACE_Proper_Import_Flag
#    define ONBOARDATCSCOMMON_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define ONBOARDATCSCOMMON_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* ONBOARDATCSCOMMON_BUILD_DLL */
#else /* ONBOARDATCSCOMMON_HAS_DLL == 1 */
#  define OnboardATCSCommon_Export
#  define ONBOARDATCSCOMMON_SINGLETON_DECLARATION(T)
#  define ONBOARDATCSCOMMON_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* ONBOARDATCSCOMMON_HAS_DLL == 1 */

// Set ONBOARDATCSCOMMON_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (ONBOARDATCSCOMMON_NTRACE)
#  if (ACE_NTRACE == 1)
#    define ONBOARDATCSCOMMON_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define ONBOARDATCSCOMMON_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !ONBOARDATCSCOMMON_NTRACE */

#if (ONBOARDATCSCOMMON_NTRACE == 1)
#  define ONBOARDATCSCOMMON_TRACE(X)
#else /* (ONBOARDATCSCOMMON_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define ONBOARDATCSCOMMON_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (ONBOARDATCSCOMMON_NTRACE == 1) */

#endif /* ONBOARDATCSCOMMON_EXPORT_H */

// End of auto generated file.
