// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.2a_p19
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:152

#ifndef _TAO_IDL_ONBOARDATCSTYPESUPPORTC_3CSZOO_H_
#define _TAO_IDL_ONBOARDATCSTYPESUPPORTC_3CSZOO_H_


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include "tao/AnyTypeCode/AnyTypeCode_methods.h"
#include "tao/AnyTypeCode/Any.h"
#include "tao/ORB.h"
#include "tao/SystemException.h"
#include "tao/Basic_Types.h"
#include "tao/ORB_Constants.h"
#include "dds/DCPS/ZeroCopyInfoSeq_T.h"
#include "dds/DCPS/ZeroCopySeq_T.h"
#include "tao/Object.h"
#include "tao/String_Manager_T.h"
#include "tao/Sequence_T.h"
#include "tao/Objref_VarOut_T.h"
#include "tao/Seq_Var_T.h"
#include "tao/Seq_Out_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#include "OnboardATCSC.h"
#include "dds/DdsDcpsInfrastructureC.h"
#include "dds/DdsDcpsPublicationC.h"
#include "dds/DdsDcpsSubscriptionExtC.h"
#include "dds/DdsDcpsTopicC.h"
#include "dds/DdsDcpsTypeSupportExtC.h"

#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 2 || TAO_BETA_VERSION != 0
#error This file should be regenerated with TAO_IDL
#endif

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO 

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:38

namespace OnboardATCS
{

  // TAO_IDL - Generated from
  // be/be_visitor_sequence/sequence_ch.cpp:102

  typedef ::TAO::DCPS::ZeroCopyDataSeq< OnboardATCS::TrainMessage, DCPS_ZERO_COPY_SEQ_DEFAULT_SIZE> TrainMessageSeq;
  

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_TrainMessageSeq;

  // TAO_IDL - Generated from
  // be/be_interface.cpp:751

#if !defined (_ONBOARDATCS_TRAINMESSAGETYPESUPPORT__VAR_OUT_CH_)
#define _ONBOARDATCS_TRAINMESSAGETYPESUPPORT__VAR_OUT_CH_

  class TrainMessageTypeSupport;
  typedef TrainMessageTypeSupport *TrainMessageTypeSupport_ptr;

  typedef
    TAO_Objref_Var_T<
        TrainMessageTypeSupport
      >
    TrainMessageTypeSupport_var;
  
  typedef
    TAO_Objref_Out_T<
        TrainMessageTypeSupport
      >
    TrainMessageTypeSupport_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:43

  class  TrainMessageTypeSupport
    : public virtual ::OpenDDS::DCPS::TypeSupport
  
  {
  public:

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    typedef TrainMessageTypeSupport_ptr _ptr_type;
    typedef TrainMessageTypeSupport_var _var_type;
    typedef TrainMessageTypeSupport_out _out_type;

    static void _tao_any_destructor (void *);

    // The static operations.
    static TrainMessageTypeSupport_ptr _duplicate (TrainMessageTypeSupport_ptr obj);

    static void _tao_release (TrainMessageTypeSupport_ptr obj);

    static TrainMessageTypeSupport_ptr _narrow (::CORBA::Object_ptr obj);
    static TrainMessageTypeSupport_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static TrainMessageTypeSupport_ptr _nil (void);

    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    TrainMessageTypeSupport (void);

    

    virtual ~TrainMessageTypeSupport (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    ACE_UNIMPLEMENTED_FUNC (TrainMessageTypeSupport (const TrainMessageTypeSupport &))
#if defined (ACE_HAS_CPP11)
    ACE_UNIMPLEMENTED_FUNC (TrainMessageTypeSupport (TrainMessageTypeSupport &&))
#endif /* ACE_HAS_CPP11 */
    ACE_UNIMPLEMENTED_FUNC (TrainMessageTypeSupport &operator= (const TrainMessageTypeSupport &))
#if defined (ACE_HAS_CPP11)
    ACE_UNIMPLEMENTED_FUNC (TrainMessageTypeSupport &operator= (TrainMessageTypeSupport &&))
#endif /* ACE_HAS_CPP11 */
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_TrainMessageTypeSupport;

  // TAO_IDL - Generated from
  // be/be_interface.cpp:751

#if !defined (_ONBOARDATCS_TRAINMESSAGEDATAWRITER__VAR_OUT_CH_)
#define _ONBOARDATCS_TRAINMESSAGEDATAWRITER__VAR_OUT_CH_

  class TrainMessageDataWriter;
  typedef TrainMessageDataWriter *TrainMessageDataWriter_ptr;

  typedef
    TAO_Objref_Var_T<
        TrainMessageDataWriter
      >
    TrainMessageDataWriter_var;
  
  typedef
    TAO_Objref_Out_T<
        TrainMessageDataWriter
      >
    TrainMessageDataWriter_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:43

  class  TrainMessageDataWriter
    : public virtual ::DDS::DataWriter
  
  {
  public:

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    typedef TrainMessageDataWriter_ptr _ptr_type;
    typedef TrainMessageDataWriter_var _var_type;
    typedef TrainMessageDataWriter_out _out_type;

    static void _tao_any_destructor (void *);

    // The static operations.
    static TrainMessageDataWriter_ptr _duplicate (TrainMessageDataWriter_ptr obj);

    static void _tao_release (TrainMessageDataWriter_ptr obj);

    static TrainMessageDataWriter_ptr _narrow (::CORBA::Object_ptr obj);
    static TrainMessageDataWriter_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static TrainMessageDataWriter_ptr _nil (void);

    virtual ::DDS::InstanceHandle_t register_instance (
      const ::OnboardATCS::TrainMessage & instance) = 0;

    virtual ::DDS::InstanceHandle_t register_instance_w_timestamp (
      const ::OnboardATCS::TrainMessage & instance,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance (
      const ::OnboardATCS::TrainMessage & instance,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance_w_timestamp (
      const ::OnboardATCS::TrainMessage & instance,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t write (
      const ::OnboardATCS::TrainMessage & instance_data,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t write_w_timestamp (
      const ::OnboardATCS::TrainMessage & instance_data,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t dispose (
      const ::OnboardATCS::TrainMessage & instance_data,
      ::DDS::InstanceHandle_t instance_handle) = 0;

    virtual ::DDS::ReturnCode_t dispose_w_timestamp (
      const ::OnboardATCS::TrainMessage & instance_data,
      ::DDS::InstanceHandle_t instance_handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::OnboardATCS::TrainMessage & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::OnboardATCS::TrainMessage & instance_data) = 0;

    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    TrainMessageDataWriter (void);

    

    virtual ~TrainMessageDataWriter (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    ACE_UNIMPLEMENTED_FUNC (TrainMessageDataWriter (const TrainMessageDataWriter &))
#if defined (ACE_HAS_CPP11)
    ACE_UNIMPLEMENTED_FUNC (TrainMessageDataWriter (TrainMessageDataWriter &&))
#endif /* ACE_HAS_CPP11 */
    ACE_UNIMPLEMENTED_FUNC (TrainMessageDataWriter &operator= (const TrainMessageDataWriter &))
#if defined (ACE_HAS_CPP11)
    ACE_UNIMPLEMENTED_FUNC (TrainMessageDataWriter &operator= (TrainMessageDataWriter &&))
#endif /* ACE_HAS_CPP11 */
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_TrainMessageDataWriter;

  // TAO_IDL - Generated from
  // be/be_interface.cpp:751

#if !defined (_ONBOARDATCS_TRAINMESSAGEDATAREADER__VAR_OUT_CH_)
#define _ONBOARDATCS_TRAINMESSAGEDATAREADER__VAR_OUT_CH_

  class TrainMessageDataReader;
  typedef TrainMessageDataReader *TrainMessageDataReader_ptr;

  typedef
    TAO_Objref_Var_T<
        TrainMessageDataReader
      >
    TrainMessageDataReader_var;
  
  typedef
    TAO_Objref_Out_T<
        TrainMessageDataReader
      >
    TrainMessageDataReader_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:43

  class  TrainMessageDataReader
    : public virtual ::OpenDDS::DCPS::DataReaderEx
  
  {
  public:

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    typedef TrainMessageDataReader_ptr _ptr_type;
    typedef TrainMessageDataReader_var _var_type;
    typedef TrainMessageDataReader_out _out_type;

    static void _tao_any_destructor (void *);

    // The static operations.
    static TrainMessageDataReader_ptr _duplicate (TrainMessageDataReader_ptr obj);

    static void _tao_release (TrainMessageDataReader_ptr obj);

    static TrainMessageDataReader_ptr _narrow (::CORBA::Object_ptr obj);
    static TrainMessageDataReader_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static TrainMessageDataReader_ptr _nil (void);

    virtual ::DDS::ReturnCode_t read (
      ::OnboardATCS::TrainMessageSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take (
      ::OnboardATCS::TrainMessageSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_w_condition (
      ::OnboardATCS::TrainMessageSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_w_condition (
      ::OnboardATCS::TrainMessageSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_sample (
      ::OnboardATCS::TrainMessage & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t take_next_sample (
      ::OnboardATCS::TrainMessage & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t read_instance (
      ::OnboardATCS::TrainMessageSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_instance (
      ::OnboardATCS::TrainMessageSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_instance_w_condition (
      ::OnboardATCS::TrainMessageSeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_instance_w_condition (
      ::OnboardATCS::TrainMessageSeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance (
      ::OnboardATCS::TrainMessageSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance (
      ::OnboardATCS::TrainMessageSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance_w_condition (
      ::OnboardATCS::TrainMessageSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance_w_condition (
      ::OnboardATCS::TrainMessageSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t return_loan (
      ::OnboardATCS::TrainMessageSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::OnboardATCS::TrainMessage & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::OnboardATCS::TrainMessage & instance_data) = 0;

    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    TrainMessageDataReader (void);

    

    virtual ~TrainMessageDataReader (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    ACE_UNIMPLEMENTED_FUNC (TrainMessageDataReader (const TrainMessageDataReader &))
#if defined (ACE_HAS_CPP11)
    ACE_UNIMPLEMENTED_FUNC (TrainMessageDataReader (TrainMessageDataReader &&))
#endif /* ACE_HAS_CPP11 */
    ACE_UNIMPLEMENTED_FUNC (TrainMessageDataReader &operator= (const TrainMessageDataReader &))
#if defined (ACE_HAS_CPP11)
    ACE_UNIMPLEMENTED_FUNC (TrainMessageDataReader &operator= (TrainMessageDataReader &&))
#endif /* ACE_HAS_CPP11 */
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_TrainMessageDataReader;

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:67

} // module OnboardATCS

// TAO_IDL - Generated from
// be/be_visitor_arg_traits.cpp:68

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_traits.cpp:62

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{

#if !defined (_ONBOARDATCS_TRAINMESSAGETYPESUPPORT__TRAITS_)
#define _ONBOARDATCS_TRAINMESSAGETYPESUPPORT__TRAITS_

  template<>
  struct  Objref_Traits< ::OnboardATCS::TrainMessageTypeSupport>
  {
    static ::OnboardATCS::TrainMessageTypeSupport_ptr duplicate (
        ::OnboardATCS::TrainMessageTypeSupport_ptr p);
    static void release (
        ::OnboardATCS::TrainMessageTypeSupport_ptr p);
    static ::OnboardATCS::TrainMessageTypeSupport_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::OnboardATCS::TrainMessageTypeSupport_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_ONBOARDATCS_TRAINMESSAGEDATAWRITER__TRAITS_)
#define _ONBOARDATCS_TRAINMESSAGEDATAWRITER__TRAITS_

  template<>
  struct  Objref_Traits< ::OnboardATCS::TrainMessageDataWriter>
  {
    static ::OnboardATCS::TrainMessageDataWriter_ptr duplicate (
        ::OnboardATCS::TrainMessageDataWriter_ptr p);
    static void release (
        ::OnboardATCS::TrainMessageDataWriter_ptr p);
    static ::OnboardATCS::TrainMessageDataWriter_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::OnboardATCS::TrainMessageDataWriter_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_ONBOARDATCS_TRAINMESSAGEDATAREADER__TRAITS_)
#define _ONBOARDATCS_TRAINMESSAGEDATAREADER__TRAITS_

  template<>
  struct  Objref_Traits< ::OnboardATCS::TrainMessageDataReader>
  {
    static ::OnboardATCS::TrainMessageDataReader_ptr duplicate (
        ::OnboardATCS::TrainMessageDataReader_ptr p);
    static void release (
        ::OnboardATCS::TrainMessageDataReader_ptr p);
    static ::OnboardATCS::TrainMessageDataReader_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::OnboardATCS::TrainMessageDataReader_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_interface/any_op_ch.cpp:44



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace OnboardATCS
{
   void operator<<= ( ::CORBA::Any &, TrainMessageTypeSupport_ptr); // copying
   void operator<<= ( ::CORBA::Any &, TrainMessageTypeSupport_ptr *); // non-copying
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, TrainMessageTypeSupport_ptr &);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, OnboardATCS::TrainMessageTypeSupport_ptr); // copying
 void operator<<= (::CORBA::Any &, OnboardATCS::TrainMessageTypeSupport_ptr *); // non-copying
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, OnboardATCS::TrainMessageTypeSupport_ptr &);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_interface/any_op_ch.cpp:44



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace OnboardATCS
{
   void operator<<= ( ::CORBA::Any &, TrainMessageDataWriter_ptr); // copying
   void operator<<= ( ::CORBA::Any &, TrainMessageDataWriter_ptr *); // non-copying
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, TrainMessageDataWriter_ptr &);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, OnboardATCS::TrainMessageDataWriter_ptr); // copying
 void operator<<= (::CORBA::Any &, OnboardATCS::TrainMessageDataWriter_ptr *); // non-copying
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, OnboardATCS::TrainMessageDataWriter_ptr &);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_interface/any_op_ch.cpp:44



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace OnboardATCS
{
   void operator<<= ( ::CORBA::Any &, TrainMessageDataReader_ptr); // copying
   void operator<<= ( ::CORBA::Any &, TrainMessageDataReader_ptr *); // non-copying
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, TrainMessageDataReader_ptr &);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, OnboardATCS::TrainMessageDataReader_ptr); // copying
 void operator<<= (::CORBA::Any &, OnboardATCS::TrainMessageDataReader_ptr *); // non-copying
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, OnboardATCS::TrainMessageDataReader_ptr &);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_codegen.cpp:1703
#if defined (__ACE_INLINE__)
#include "OnboardATCSTypeSupportC.inl"
#endif /* defined INLINE */

#endif /* ifndef */

